name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install --legacy-peer-deps
      
    - name: Build Next.js app
      run: npm run build
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install Capacitor
      run: npm install @capacitor/core @capacitor/cli @capacitor/android --legacy-peer-deps
      
    - name: Add Android platform
      run: npx cap add android
      
    - name: Sync project
      run: npx cap sync android
      
    - name: Build APK
      run: |
        cd android
        ./gradlew assembleDebug
      env:
        ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
        
    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v2
      with:
        files: android/app/build/outputs/apk/debug/app-debug.apk
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          APK build from commit ${{ github.sha }}
          
          Built by: ${{ github.actor }}
          Email: ff23301@163.com
          Username: cffa-as
          
          ## 安装说明
          1. 下载APK文件
          2. 在Android设备上启用"未知来源"应用安装
          3. 安装APK文件
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 